// <auto-generated />
namespace pharm4me7.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EditPhoneDataType : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EditPhoneDataType));
        
        string IMigrationMetadata.Id
        {
            get { return "201810291055580_EditPhoneDataType"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
