// <auto-generated />
namespace pharm4me7.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class patientOrderedColumnAdd : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(patientOrderedColumnAdd));
        
        string IMigrationMetadata.Id
        {
            get { return "201812160347369_patientOrderedColumnAdd"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
